version: '3.8'
services:
  postgres-db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - "internal-networks"
networks:
  internal-networks:
    name: "${APP_NAME}"
    driver: bridge
volumes:
  postgres-data: